version: '3'

services:
  MariaDB:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"  # on indique le port qui sera exposé à la machine locale
    restart: on-failure

	wordpress:
		container_name: wordpress
		networks:
		  - inception
		build: 
		  context: requirements/wordpress
		  dockerfile: Dockerfile
		env_file: .env
		volumes:
		  - wordpress: /var/www/wordpress
		depends_on:    					# WordPress démarrera uniquement après MariaDB (sinon il ne pourra pas configurer la base de données...)
		  - mariadb
		restart: on-failure
		expose: 
		  - "9000"

	volumes:
		wordpress:
			driver: local # ici nous stockons le volume en local
			driver_opts:
			type: 'none' 									# aucun type spécifique
			o: 'bind
			device: '/home/armand/data/wordpress' 		#Ou stocker le dossier sur votre ordinateur en local
		mariadb:
			driver: local
			driver_opts:
			type: 'none' 
			o: 'bind'										 # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
			device: '/home/armand/data/mariadb'			#Ou stocker le dossier sur votre ordinateur en local

    networks:
	    inception:
	    driver: bridge